# make it explicit to prefer container-based travis workers
sudo: false

language: python

cache:
  apt: true
  directories:
    - $HOME/.cache/pip
    - $HOME/download

branches:
  except:
    - gh-pages

install: source .travis_install.sh
# command to run tests, e.g. python setup.py test
script:
  - coverage run --source=planet4 setup.py test

after_success:
    - coveralls
    # - codecov

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b4b9edd321cd6608b49f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
