sudo: false
language: python

cache: pip

branches:
  except:
    - gh-pages

python:
  - "3.5"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION --file requirements.txt
  - conda install --yes pytest
  - pip install git+https://github.com/zonca/pytest-ipynb.git
  - pip install --pre .

# command to run tests, e.g. python setup.py test
script:
    - cd notebooks/tests
    - py.test -v

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b4b9edd321cd6608b49f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
